apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: dev
spec:
  mtls:
    mode: STRICT
---
# Allow plaintext from Nginx Ingress (outside mesh) to storefront-bff
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: storefront-bff-mtls-override
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storefront-bff
  mtls:
    mode: PERMISSIVE
---
# Allow plaintext from Nginx Ingress (outside mesh) to backoffice-bff
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: backoffice-bff-mtls-override
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backoffice-bff
  mtls:
    mode: PERMISSIVE
---
# Allow plaintext from Nginx Ingress (outside mesh) to swagger-ui
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: swagger-ui-mtls-override
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: swagger-ui
  mtls:
    mode: PERMISSIVE
---
# Allow plaintext from Nginx Ingress (outside mesh) to media (for serving product images)
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: media-mtls-override
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: media
  mtls:
    mode: PERMISSIVE
