global:
  environment: dev

backend:
  extraEnvs:
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
      value: "http://identity.yas.local.com/realms/Yas"
    - name: PGSSLMODE
      value: "disable"
    - name: JAVA_TOOL_OPTIONS
      value: "-XX:+UseSerialGC -Xmx256m -XX:TieredStopAtLevel=1"
  resources:
    requests:
      memory: "384Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
  livenessProbe:
    initialDelaySeconds: 120
    failureThreshold: 30
  readinessProbe:
    initialDelaySeconds: 120
    failureThreshold: 30
